# Generated by Django 5.1.6 on 2025-03-28 07:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày khởi tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Xóa')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Ngày xóa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tên chủ đề')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả chủ đề')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người khởi tạo')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Người xóa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': 'Chủ đề tin tức',
                'verbose_name_plural': 'Chủ đề tin tức',
                'db_table': 'tb_news_topic',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày khởi tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Xóa')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Ngày xóa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề bài viết')),
                ('content', models.TextField(verbose_name='Nội dung bài viết')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Hình ảnh minh họa')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='Tác giả')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người khởi tạo')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Người xóa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
                ('news_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_topic_article', to='app_news_information.newstopic', verbose_name='Chủ đề tin tức')),
            ],
            options={
                'verbose_name': 'Tin tức',
                'verbose_name_plural': 'Tin tức',
                'db_table': 'tb_news_article',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
