# Generated by Django 5.1.6 on 2025-03-28 09:37

import backend.custom.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news_information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=backend.custom.functions.upload_to, verbose_name='Hình ảnh minh họa'),
        ),
    ]
