# Generated by Django 5.1.6 on 2025-03-24 02:18

import backend.custom.functions
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitionArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày khởi tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Xóa')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Ngày xóa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tên khu vực')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả khu vực')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Vị trí')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người khởi tạo')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Người xóa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': 'Khu vực trưng bày',
                'verbose_name_plural': 'Khu vực trưng bày',
                'db_table': 'tb_exhibition_area',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExhibitionContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày khởi tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Xóa')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Ngày xóa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề nội dung')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả nội dung')),
                ('content_type', models.CharField(choices=[('artifact', 'Hiện vật'), ('image', 'Hình ảnh'), ('video', 'Video'), ('document', 'Tài liệu'), ('interactive', 'Tương tác số')], max_length=100, verbose_name='Kiểu nội dung')),
                ('file', models.FileField(blank=True, null=True, upload_to=backend.custom.functions.upload_to, verbose_name='Tệp nội dung')),
                ('video', models.FileField(blank=True, null=True, upload_to=backend.custom.functions.upload_to, verbose_name='Video nội dung')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người khởi tạo')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Người xóa')),
                ('exhibition_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='app_exhibition_visit.exhibitionarea', verbose_name='Khu vực trưng bày')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': 'Nội dung trưng bày',
                'verbose_name_plural': 'Nội dung trưng bày',
                'db_table': 'tb_exbihition_content',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày khởi tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Xóa')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Ngày xóa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('origin', models.CharField(blank=True, max_length=255, verbose_name='Nguồn gốc')),
                ('material', models.CharField(blank=True, max_length=255, verbose_name='Chất liệu')),
                ('year', models.CharField(blank=True, max_length=255, verbose_name='Niên đại')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người khởi tạo')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Người xóa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
                ('exhibition_content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_exhibition_visit.exhibitioncontent', verbose_name='Nội dung trưng bày')),
            ],
            options={
                'verbose_name': 'Hiện vật',
                'verbose_name_plural': 'Hiện vật',
                'db_table': 'tb_artifact',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
