# Generated by Django 5.1.6 on 2025-03-24 07:39

import backend.custom.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_exhibition_visit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitioncontent',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=backend.custom.functions.upload_to, verbose_name='Hình ảnh nội dung'),
        ),
        migrations.AlterField(
            model_name='exhibitioncontent',
            name='content_type',
            field=models.CharField(choices=[('artifact', 'Hiện vật'), ('image', 'Hình ảnh'), ('video', 'Video'), ('document', 'Tài liệu')], max_length=100, verbose_name='Kiểu nội dung'),
        ),
    ]
