# Generated by Django 5.1.6 on 2025-03-26 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_exhibition_visit', '0002_exhibitioncontent_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='exhibition_content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artifact', to='app_exhibition_visit.exhibitioncontent', verbose_name='Nội dung trưng bày'),
        ),
    ]
