# Generated by Django 5.1.6 on 2025-03-26 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_exhibition_visit', '0003_alter_artifact_exhibition_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='exhibition_content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_content_artifact', to='app_exhibition_visit.exhibitioncontent', verbose_name='Nội dung trưng bày'),
        ),
        migrations.AlterField(
            model_name='exhibitioncontent',
            name='exhibition_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_area_content', to='app_exhibition_visit.exhibitionarea', verbose_name='Khu vực trưng bày'),
        ),
    ]
