# Generated by Django 5.1.6 on 2025-04-02 07:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_historical_figures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistorycalFigure',
            new_name='HistoricalFigure',
        ),
    ]
