# Generated by Django 5.1.6 on 2025-04-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_historical_figures', '0002_rename_historycalfigure_historicalfigure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalfilm',
            name='approve',
            field=models.BooleanField(default=False, verbose_name='Phê duyệt thông tin'),
        ),
    ]
