# Generated by Django 5.1.6 on 2025-04-03 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_historical_figures', '0003_alter_historicalfilm_approve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalfigure',
            old_name='approve',
            new_name='is_approve',
        ),
        migrations.RenameField(
            model_name='historicalfilm',
            old_name='approve',
            new_name='is_approve',
        ),
    ]
